### ISSUE TITLE
Disponer de una versión compilada lista para descargar

### ISSUE THREAD

**Issue by eusonlito** [universitatjaumei/cryptoapplet#1]
Al igual que la mayoría de proyectos de Javascript, Java y CSS, sería muy útil disponer de un directorio con todo lo necesario con la última versión ya compilada lista para implementar.

**Comment by eusonlito** [comment]
Como nota, ya conocía la documentación sobre compilación publicada en http://jira.uji.es/confluence/pages/viewpage.action?pageId=26739320 pero si se puede descargar ya la versión compilada acelera el trabajo :)

**Comment by borillo** [comment]
La versión compilada está también disponible desde la documentación:

http://jira.uji.es/confluence/display/CRYPTOAPPLET/Distribuciones+de+CryptoApplet

---

# Salut,

Ricardo Borillo Domenech ~ @borillo
http://xml-utils.com

2014-03-21 23:01 GMT+01:00 eusonlito notifications@github.com:

**Comment by eusonlito** [comment]
Entiendo que esto ahora no es posible al necesitar que todos los applets java estén firmados por alguna entidad validada. Y no creo que vosotros vayais a pagar la firma de applets que distribuyen terceros :)

**Comment by borillo** [comment]
No, lo siento :(
Y nos nada barato el dichoso certificado de firma de código ...

Si te sirve, hicimos una review de las opciones que había en su momento y tiramos por DigiCert que era la más asequible. 

Ahora habría que volver a ver.

**Comment by eusonlito** [comment]
Simplemente como comentario, nosotros usamos GoDaddy, que valoramos como el más económico y que reúne todas las garantías de firma https://es.godaddy.com/ssl/code-signing-certificate.aspx

Saludos y gracias por todo.

**Comment by borillo** [comment]
Lo tendremos en cuenta para la próxima renovación :)

Gracias a ti
