### ISSUE TITLE
El proyecto no compila

### ISSUE THREAD

**Issue by RoseTr** [universitatjaumei/cryptoapplet#5]
Falla porque no encuentra la versión 3.3.2 de afirma-crypto-pdf.
En el repo público la versión que aparece es la 3.3.1.

**Comment by borillo** [comment]
¿Puedes probar de nuevo?
Ya están las SNAPSHOTS de @firma subidas al repositorio y debería compilar sin problemas:

http://devel.uji.es/nexus/content/repositories/snapshots/es/gob/afirma/
