### ISSUE TITLE
Wrong extendedKeyUsage check in X509CertificateHandler.java

### ISSUE THREAD

**Issue by totszwai** [universitatjaumei/cryptoapplet#7]
https://github.com/universitatjaumei/cryptoapplet/blame/master/uji-keystore/src/main/java/es/uji/security/keystore/X509CertificateHandler.java#L281

Should be checking for 1.3.6.1.5.5.7.3.4 (SMIME) and not 1.3.6.1.5.5.7.3.2

**Comment by totszwai** [comment]
Should also add the following at the end of getKeyUsage()

        if (_keyUsage[2])   // keyEncipherment
            _emailProtection = true;

**Comment by totszwai** [comment]
public String getKeyUsage()
    {
        String auxStr = "";

        // System.out.println("Parseando keyUsage...");

        if (_keyUsage != null)
        {

            for (int i = 0; i < _keyUsage.length; i++)
            {
                if (_keyUsage[i])
                {
                    auxStr += _keyUsageStr[i] + ", ";
                    // System.out.println("pillado usage: " + auxStr);
                }
            }
            auxStr = auxStr.substring(0, auxStr.length() - 2);
        }

        if (_extKeyUsage != null)
        {
            for (String u : _extKeyUsage)
            {
                //if (u.equals("1.3.6.1.5.5.7.3.2")) // wrong
                if (u.equals("1.3.6.1.5.5.7.3.4"))
                {
                    _emailProtection = true;
                }
            }
        }
        
        if (_keyUsage[2])   // keyEncipherment
            _emailProtection = true;

        return auxStr;
    }

**Comment by borillo** [comment]
Hi @totszwai, Thx for your comments. Can you please submit a pull request?

**Comment by borillo** [comment]
Merged at e073fb8150026736d2cb18ea6853dfcf317a72ec
