### ISSUE TITLE
Exception in extractSubjectFromDN if there is no "CN="

### ISSUE THREAD

**Issue by totszwai** [universitatjaumei/cryptoapplet#8]
The following line will throw exception if there is no "CN=" in the SubjectDN

    String auxStr = _SubjectDN.substring(_SubjectDN.indexOf("CN="));

The fix should be 

        int auxIdx = _SubjectDN.indexOf("CN=");
        if (auxIdx <= -1) {
            _SubjectCN = "";
            return;
        }

        String auxStr = _SubjectDN.substring(auxIdx);

**Comment by borillo** [comment]
Hi @totszwai, Thx for your comments. Can you please submit a pull request?

**Comment by borillo** [comment]
Merged at e073fb8150026736d2cb18ea6853dfcf317a72ec
